"""description

Revision ID: 07538d0e031c
Revises: e8ad4e90ebb8
Create Date: 2024-11-14 21:23:52.807059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07538d0e031c'
down_revision = 'e8ad4e90ebb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
