"""Database creation

Revision ID: 22bad8695bb4
Revises: 
Create Date: 2024-10-12 18:43:16.599395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bad8695bb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('person_surname', sa.String(), nullable=True),
    sa.Column('person_patronimic', sa.String(), nullable=True),
    sa.Column('person_age', sa.Integer(), nullable=True),
    sa.Column('person_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('training',
    sa.Column('training_id', sa.UUID(), nullable=False),
    sa.Column('training_name', sa.String(), nullable=True),
    sa.Column('training_description', sa.String(), nullable=True),
    sa.Column('training_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('training_status', sa.Integer(), nullable=True),
    sa.Column('training_space', sa.Integer(), nullable=True),
    sa.Column('training_free_space', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('training_id')
    )
    op.create_table('training_sign',
    sa.Column('sign_id', sa.UUID(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_sign')
    op.drop_table('training')
    op.drop_table('person')
    # ### end Alembic commands ###
