"""rm freespace

Revision ID: 382eff89be38
Revises: 77e8071f7e2b
Create Date: 2024-11-08 16:38:03.520208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382eff89be38'
down_revision = '77e8071f7e2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'training_free_space')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('training_free_space', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
