"""description

Revision ID: 3c8402c4522c
Revises: d8cb22af90e8
Create Date: 2024-11-08 09:43:54.368139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8402c4522c'
down_revision = 'd8cb22af90e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'training_free_space')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('training_free_space', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
