"""trainer_pic

Revision ID: 54031135f3da
Revises: 69599553a7dd
Create Date: 2024-11-20 15:42:38.013656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54031135f3da'
down_revision = '69599553a7dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_picture',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['trainer.trainer_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_picture')
    # ### end Alembic commands ###
