"""description

Revision ID: 77e8071f7e2b
Revises: 3c8402c4522c
Create Date: 2024-11-08 11:41:59.835482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e8071f7e2b'
down_revision = '3c8402c4522c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('training_free_space', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'training_free_space')
    # ### end Alembic commands ###
