"""description

Revision ID: b398b4de720d
Revises: a43bb279ba38
Create Date: 2024-11-11 19:55:10.899487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b398b4de720d'
down_revision = 'a43bb279ba38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
