"""description

Revision ID: d8cb22af90e8
Revises: 9238b57e8313
Create Date: 2024-11-08 09:39:12.353252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cb22af90e8'
down_revision = '9238b57e8313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'picture')
    # ### end Alembic commands ###
